name: Build openssh-portable-win32

on:
  push:
    branches: [ debug-actions ]
  workflow_dispatch:
    # inputs:
    #   patch_name:
    #     required: true
    #     default: 'main.patch'

jobs:
  patch-and-build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64, ARM, ARM64]
        config: [Release, Debug]

    steps:
      - name: Checkout upstream
        uses: actions/checkout@v4
        with:
          repository: 'PowerShell/openssh-portable'
          path: openssh-portable

      - name: Build and Package
        shell: powershell
        run: |
          cd openssh-portable
          ipmo .\contrib\win32\openssh\OpenSSHBuildHelper.psm1 -Force
          Start-OpenSSHBuild -Configuration ${{ matrix.config }} -NativeHostArch ${{ matrix.arch }}

#      - name: Setup Windows SDK
#        shell: powershell
#        run: |
#          Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
#          Install-Module -Name VSSetup -Force
#
#      - name: Setup MSBuild
#        uses: microsoft/setup-msbuild@v2
#
#      - name: Build and Package
#        run: |
#          cd openssh-portable
#          msbuild contrib\win32\openssh\Win32-OpenSSH.sln `
#            /p:Configuration=${{ matrix.config }} `
#            /p:Platform=${{ matrix.arch }} `
#            /p:OutputPath=bin\${{ matrix.arch }}\${{ matrix.config }}\

      - name: Package to Zip
        shell: pwsh
        run: |
          $zipName = "ObfuscatedOpenSSH_Windows_${{ matrix.arch }}_${{ matrix.config }}.zip"
          $targetPath = "openssh-portable\bin\${{ matrix.arch }}\${{ matrix.config }}\"
          Compress-Archive -Path "$targetPath*" -DestinationPath $zipName

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.arch }}-${{ matrix.config }}
          path: "*.zip"
