name: Build openssh-portable-win32

on:
  push:
    branches: [ debug-actions ]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag to build (leave empty for latest)'
        required: false
        default:

jobs:
  patch-and-build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86] # [x86, x64, ARM, ARM64]
        config: [Release] #[Release, Debug]

    steps:
      - name: Checkout upstream
        uses: actions/checkout@v4
        with:
          repository: "PowerShell/openssh-portable"
          ref: ${{ github.event.inputs.tag_name != '' && github.event.inputs.tag_name || 'v9.8.3.0' }}
          path: openssh-portable
          fetch-depth: 1

      - name: Bootstrap vcpkg
        working-directory: ./openssh-portable
        run: .\bootstrap-vcpkg.bat

      - name: Integrate vcpkg
        working-directory: .\openssh-portable
        run: .\vcpkg.exe integrate install

      - name: Build OpenSSH
        working-directory: .\openssh-portable
        shell: powershell
        run: |
          ipmo .\contrib\win32\openssh\BuildHelper.psm1 -Force
          Start-OpenSSHBuild -Configuration Release -NativeHostArch x64

      - name: Build and Package
        working-directory: .\openssh-portable
        shell: powershell
        run: |
          cd openssh-portable
          ipmo .\contrib\win32\openssh\OpenSSHBuildHelper.psm1 -Force
          Start-OpenSSHBuild -Configuration ${{ matrix.config }} -NativeHostArch ${{ matrix.arch }}

#      - name: Setup Windows SDK
#        shell: powershell
#        run: |
#          Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
#          Install-Module -Name VSSetup -Force
#
#      - name: Setup MSBuild
#        uses: microsoft/setup-msbuild@v2
#
#      - name: Build and Package
#        run: |
#          cd openssh-portable
#          msbuild contrib\win32\openssh\Win32-OpenSSH.sln `
#            /p:Configuration=${{ matrix.config }} `
#            /p:Platform=${{ matrix.arch }} `
#            /p:OutputPath=bin\${{ matrix.arch }}\${{ matrix.config }}\

      - name: Package to Zip
        working-directory: .\openssh-portable
        shell: pwsh
        run: |
          $zipName = "ObfuscatedOpenSSH_Windows_${{ matrix.arch }}_${{ matrix.config }}.zip"
          $targetPath = "openssh-portable\bin\${{ matrix.arch }}\${{ matrix.config }}\"
          Compress-Archive -Path "$targetPath*" -DestinationPath $zipName

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.arch }}-${{ matrix.config }}
          path: "*.zip"
